local p = require("cobalt2.palette")

---@return table<string, vim.api.keyset.highlight>
local function ui()
	return {
		Normal = { fg = p.fg, bg = p.bg },
		NormalNC = { fg = p.fg, bg = p.bg },
		Cursor = { fg = p.yellow, bg = p.bg },
		CursorLine = { bg = p.cursor_line },
		CursorColumn = { bg = p.cursor_hover },
		CursorLineNr = { fg = p.yellow, bold = true },
		LineNr = { fg = p.light_grey, bg = p.bg },
		ColorColumn = { bg = p.dark_red },
		Visual = { bg = p.selection },
		VisualNOS = { bg = p.darker_blue },
		Search = { fg = p.black, bg = p.blue },
		IncSearch = { fg = p.black, bg = p.yellow },
		CurSearch = { fg = p.black, bg = p.yellow },
		MatchParen = { fg = p.fg, bg = p.dark_purple, bold = true },
		StatusLine = { fg = p.yellow, bg = p.cursor_line },
		StatusLineNC = { fg = p.fg, bg = p.cursor_line },
		StatusLineTerm = { fg = p.black, bg = p.green, bold = true },
		StatusLineTermNC = { fg = p.black, bg = p.green },
		TabLine = { fg = p.yellow, bg = p.cursor_hover },
		TabLineFill = { fg = p.light_grey, bg = p.bg_dark },
		TabLineSel = { fg = p.fg, bg = p.bg, bold = true },
		WinSeparator = { fg = p.grey },
		WinBar = { fg = p.yellow, bold = true },
		WinBarNC = { fg = p.yellow },
		VertSplit = { fg = p.grey },
		Pmenu = { fg = p.light_grey, bg = p.bg_float },
		PmenuSel = { fg = p.black, bg = p.yellow },
		PmenuSbar = { bg = p.grey },
		PmenuThumb = { bg = p.lighter_grey },
		NormalFloat = { fg = p.fg, bg = p.bg_float },
		FloatBorder = { fg = p.blue, bg = p.bg },
		FloatTitle = { fg = p.yellow, bg = p.darker_blue },
		FloatFooter = { link = "FloatTitle" },
		FloatShadow = { bg = p.black, blend = 80 },
		FloatShadowThrough = { bg = p.black, blend = 100 },
		SignColumn = { fg = p.bg, bg = p.bg },
		Folded = { fg = p.light_grey, bg = p.cursor_line, italic = true },
		FoldColumn = { fg = p.grey, bg = p.bg },
		DiffAdd = { fg = p.green, bg = p.bg },
		DiffChange = { fg = p.green, bg = p.bg },
		DiffDelete = { fg = p.red, bg = p.bg },
		DiffText = { fg = p.fg, bg = p.bg, bold = true },
		Directory = { fg = p.blue },
		ErrorMsg = { fg = p.error },
		WarningMsg = { fg = p.light_yellow },
		ModeMsg = { bold = true },
		MoreMsg = { fg = p.blue },
		Question = { fg = p.green },
		NonText = { fg = p.grey, bg = p.bg },
		SpecialKey = { fg = p.light_blue, bg = p.bg },
		Whitespace = { fg = p.grey },
		WildMenu = { fg = p.blue, bg = p.yellow },
		Conceal = { fg = p.grey },
		SpellBad = { sp = p.red, undercurl = true },
		SpellCap = { sp = p.blue, undercurl = true },
		SpellLocal = { sp = p.green, undercurl = true },
		SpellRare = { sp = p.pink, undercurl = true },
		Todo = { fg = p.orange, italic = true },
		Error = { fg = p.fg, bg = p.error, italic = true },
		Added = { fg = p.green },
		Changed = { fg = p.blue },
		Removed = { fg = p.red },
		QuickFixLine = { bg = p.cursor_hover },
		MsgSeparator = { link = "StatusLine" },
		TermCursor = { reverse = true },
		RedrawDebugNormal = { reverse = true },
		RedrawDebugClear = { bg = p.yellow },
		RedrawDebugComposed = { bg = p.green },
		RedrawDebugRecompose = { bg = p.red },
		ComplMatchIns = {},
		SnippetTabstop = { link = "Visual" },
		SnippetTabstopActive = { link = "SnippetTabstop" },
	}
end

---@return table<string, vim.api.keyset.highlight>
local function syntax()
	return {
		Comment = { fg = p.blue, italic = true },
		Constant = { fg = p.light_green },
		String = { fg = p.light_green },
		Character = { fg = p.pink },
		Number = { fg = p.pink },
		Boolean = { fg = p.pink, italic = true },
		Float = { fg = p.pink },
		Identifier = { fg = p.orange },
		Function = { fg = p.light_pink, italic = true },
		Statement = { fg = p.orange },
		Conditional = { fg = p.orange },
		Repeat = { fg = p.pink },
		Label = { fg = p.yellow },
		Operator = { fg = p.blue },
		Keyword = { fg = p.light_blue, italic = true },
		Exception = { fg = p.light_pink, italic = true },
		PreProc = { fg = p.orange },
		Include = { fg = p.pink, italic = true },
		Define = { fg = p.orange, italic = true },
		Macro = { fg = p.yellow },
		PreCondit = { fg = p.orange },
		Type = { fg = p.yellow },
		StorageClass = { fg = p.light_orange },
		Structure = { fg = p.blue, italic = true },
		Typedef = { fg = p.orange },
		Special = { fg = p.light_green },
		SpecialChar = { fg = p.pink },
		Tag = { fg = p.light_blue },
		Delimiter = { fg = p.dirty_blue },
		SpecialComment = { fg = p.light_green, italic = true },
		Debug = { fg = p.light_green, italic = true },
		Underlined = { fg = p.light_green, underline = true },
		Ignore = { fg = p.grey, italic = true },
		Title = { fg = p.green, bold = true },
		Strikethrough = { fg = p.grey, strikethrough = true },
		Rainbow1 = { fg = p.error, bold = true },
		Rainbow2 = { fg = p.orange, bold = true },
		Rainbow3 = { fg = p.yellow, bold = true },
		Rainbow4 = { fg = p.green, bold = true },
		Rainbow5 = { fg = p.blue, bold = true },
		Rainbow6 = { fg = p.type_pink, bold = true },
	}
end

---@return table<string, string>
local function links()
	return {
		VertSplit = "WinSeparator",
		WinBarNC = "WinBar",
		DiffTextAdd = "DiffText",
		EndOfBuffer = "NonText",
		LineNrAbove = "LineNr",
		LineNrBelow = "LineNr",
		CursorLineSign = "SignColumn",
		CursorLineFold = "FoldColumn",
		PmenuKind = "Pmenu",
		PmenuKindSel = "PmenuSel",
		PmenuMatch = "Pmenu",
		PmenuMatchSel = "PmenuSel",
		PmenuExtra = "Pmenu",
		PmenuExtraSel = "PmenuSel",
		PreInsert = "Added",
		ComplHint = "NonText",
		ComplHintMore = "MoreMsg",
		Substitute = "Search",
		diffAdded = "Added",
		diffRemoved = "Removed",
		diffChanged = "Changed",
		String = "Constant",
		Character = "Constant",
		Number = "Constant",
		Boolean = "Constant",
		Float = "Number",
		Function = "Function",
		Conditional = "Statement",
		Repeat = "Statement",
		Label = "Statement",
		Operator = "Statement",
		Keyword = "Statement",
		Exception = "Statement",
		Include = "PreProc",
		Define = "PreProc",
		Macro = "PreProc",
		PreCondit = "PreProc",
		StorageClass = "Type",
		Structure = "Type",
		Typedef = "Type",
		Tag = "Special",
		SpecialChar = "Special",
		Delimiter = "Special",
		SpecialComment = "Special",
		Debug = "Special",
		DiagnosticVirtualTextError = "DiagnosticError",
		DiagnosticVirtualTextWarn = "DiagnosticWarn",
		DiagnosticVirtualTextInfo = "DiagnosticInfo",
		DiagnosticVirtualTextHint = "DiagnosticHint",
		DiagnosticVirtualTextOk = "DiagnosticOk",
		DiagnosticFloatingError = "DiagnosticError",
		DiagnosticFloatingWarn = "DiagnosticWarn",
		DiagnosticFloatingInfo = "DiagnosticInfo",
		DiagnosticFloatingHint = "DiagnosticHint",
		DiagnosticFloatingOk = "DiagnosticOk",
		DiagnosticSignError = "DiagnosticError",
		DiagnosticSignWarn = "DiagnosticWarn",
		DiagnosticSignInfo = "DiagnosticInfo",
		DiagnosticSignHint = "DiagnosticHint",
		DiagnosticSignOk = "DiagnosticOk",
		DiagnosticUnnecessary = "Comment",
		LspInlayHint = "NonText",
		-- Treesitter: comments
		["@comment"] = "Comment",
		["@comment.documentation"] = "Comment",
		["@comment.todo"] = "Todo",
		["@comment.warning"] = "WarningMsg",
		["@comment.error"] = "ErrorMsg",
		["@comment.hint"] = "MoreMsg",
		["@comment.note"] = "Comment",
		-- Treesitter: constants & literals
		["@constant"] = "Constant",
		["@constant.builtin"] = "Special",
		["@constant.macro"] = "Define",
		["@string"] = "String",
		["@string.documentation"] = "String",
		["@string.escape"] = "SpecialChar",
		["@string.regexp"] = "SpecialChar",
		["@string.special"] = "SpecialChar",
		["@string.special.path"] = "Special",
		["@string.special.symbol"] = "Constant",
		["@string.special.url"] = "Underlined",
		["@character"] = "Character",
		["@character.special"] = "SpecialChar",
		["@number"] = "Number",
		["@boolean"] = "Boolean",
		["@number.float"] = "Float",
		-- Treesitter: identifiers & properties
		["@variable"] = "Identifier",
		["@variable.parameter"] = "Identifier",
		["@variable.parameter.builtin"] = "Special",
		["@variable.member"] = "Identifier",
		["@property"] = "Identifier",
		["@attribute"] = "Macro",
		["@attribute.builtin"] = "Special",
		["@module"] = "Identifier",
		["@label"] = "Label",
		-- Treesitter: functions
		["@function"] = "Function",
		["@function.call"] = "Function",
		["@function.builtin"] = "Special",
		["@function.macro"] = "Macro",
		["@function.method"] = "Function",
		["@function.method.call"] = "Function",
		["@constructor"] = "Special",
		["@constructor.lua"] = "Delimiter",
		-- Treesitter: keywords
		["@keyword"] = "Keyword",
		["@keyword.modifier"] = "Keyword",
		["@keyword.coroutine"] = "Keyword",
		["@keyword.function"] = "Keyword",
		["@keyword.operator"] = "Keyword",
		["@keyword.return"] = "Keyword",
		["@keyword.export"] = "Keyword",
		["@keyword.conditional"] = "Conditional",
		["@keyword.conditional.ternary"] = "Operator",
		["@keyword.repeat"] = "Repeat",
		["@keyword.type"] = "Structure",
		["@keyword.exception"] = "Exception",
		["@keyword.debug"] = "Debug",
		["@keyword.import"] = "Include",
		["@keyword.directive"] = "Define",
		["@keyword.directive.define"] = "Define",
		["@operator"] = "Operator",
		-- Treesitter: types
		["@type"] = "Type",
		["@type.builtin"] = "Type",
		["@type.definition"] = "Typedef",
		-- Treesitter: punctuation & tags
		["@punctuation"] = "Delimiter",
		["@punctuation.delimiter"] = "Delimiter",
		["@punctuation.bracket"] = "Delimiter",
		["@punctuation.special"] = "Special",
		["@tag"] = "Tag",
		["@tag.builtin"] = "Special",
		["@tag.attribute"] = "Macro",
		["@tag.delimiter"] = "Delimiter",
		-- Treesitter: markup
		["@markup.link"] = "Identifier",
		["@markup.link.label"] = "Identifier",
		["@markup.link.url"] = "Underlined",
		["@markup.raw"] = "Comment",
		["@markup.heading"] = "Title",
		["@markup.heading.markdown"] = "Title",
		["@markup.heading.1.markdown"] = "Rainbow1",
		["@markup.heading.2.markdown"] = "Rainbow2",
		["@markup.heading.3.markdown"] = "Rainbow3",
		["@markup.heading.4.markdown"] = "Rainbow4",
		["@markup.heading.5.markdown"] = "Rainbow5",
		["@markup.heading.6.markdown"] = "Rainbow6",
		["@markup.heading.html"] = "Title",
		["@markup.heading.1.html"] = "Title",
		["@markup.heading.2.html"] = "Title",
		["@markup.heading.3.html"] = "Title",
		["@markup.heading.4.html"] = "Title",
		["@markup.heading.5.html"] = "Title",
		["@markup.heading.6.html"] = "Title",
		["@markup.underline"] = "Underlined",
		["@markup.strikethrough"] = "Strikethrough",
		["@markup.strong"] = "Title",
		["@markup.italic"] = "SpecialComment",
		["@markup.quote"] = "Comment",
		["@markup.math"] = "Function",
		["@markup.environment"] = "PreProc",
		["@markup.environment.name"] = "Type",
		["@markup.list"] = "Label",
		["@markup.list.checked"] = "Added",
		["@markup.list.unchecked"] = "Ignore",
		-- Treesitter: diff
		["@diff.plus"] = "diffAdded",
		["@diff.minus"] = "diffRemoved",
		["@diff.delta"] = "diffChanged",
		["@error"] = "Error",
		-- Treesitter: legacy aliases
		["@parameter"] = "Identifier",
		["@field"] = "Identifier",
		["@namespace"] = "Identifier",
		["@float"] = "Float",
		["@symbol"] = "SpecialChar",
		["@method"] = "Function",
		["@method.call"] = "Function",
		["@conditional"] = "Conditional",
		["@repeat"] = "Repeat",
		["@exception"] = "Exception",
		["@include"] = "Include",
		["@define"] = "Define",
		["@preproc"] = "PreProc",
		["@storageclass"] = "Type",
		["@text"] = "Normal",
		["@text.strong"] = "Title",
		["@text.emphasis"] = "SpecialComment",
		["@text.underline"] = "Underlined",
		["@text.strike"] = "Strikethrough",
		["@text.uri"] = "Underlined",
		["@text.math"] = "Function",
		["@text.environment"] = "PreProc",
		["@text.environment.name"] = "Type",
		["@text.title"] = "Title",
		["@text.literal"] = "Comment",
		["@text.reference"] = "Identifier",
		["@text.todo"] = "Todo",
		["@text.todo.checked"] = "Added",
		["@text.todo.unchecked"] = "Ignore",
		["@text.warning"] = "WarningMsg",
		["@text.note"] = "Comment",
		["@text.danger"] = "ErrorMsg",
		["@text.diff.add"] = "diffAdded",
		["@text.diff.delete"] = "diffRemoved",
		["@text.title.1.markdown"] = "Rainbow1",
		["@text.title.2.markdown"] = "Rainbow2",
		["@text.title.3.markdown"] = "Rainbow3",
		["@text.title.4.markdown"] = "Rainbow4",
		["@text.title.5.markdown"] = "Rainbow5",
		["@text.title.6.markdown"] = "Rainbow6",
		-- LSP semantic tokens
		["@lsp.type.class"] = "Structure",
		["@lsp.type.comment"] = "Comment",
		["@lsp.type.decorator"] = "Function",
		["@lsp.type.enum"] = "Structure",
		["@lsp.type.enumMember"] = "Constant",
		["@lsp.type.function"] = "Function",
		["@lsp.type.interface"] = "Structure",
		["@lsp.type.macro"] = "Macro",
		["@lsp.type.method"] = "Function",
		["@lsp.type.namespace"] = "Structure",
		["@lsp.type.parameter"] = "Identifier",
		["@lsp.type.property"] = "Identifier",
		["@lsp.type.struct"] = "Structure",
		["@lsp.type.type"] = "Type",
		["@lsp.type.typeParameter"] = "Typedef",
		["@lsp.type.variable"] = "Identifier",
		["@lsp.typemod.function.defaultLibrary"] = "@function.builtin",
		["@lsp.typemod.function.builtin"] = "@function.builtin",
	}
end

---@return table<string, vim.api.keyset.highlight>
local function diagnostics()
	return {
		DiagnosticError = { fg = p.error },
		DiagnosticWarn = { fg = p.yellow },
		DiagnosticInfo = { fg = p.light_blue },
		DiagnosticHint = { fg = p.greyish_blue },
		DiagnosticOk = { fg = p.green },
		DiagnosticUnderlineError = { sp = p.error, undercurl = true },
		DiagnosticUnderlineWarn = { sp = p.yellow, undercurl = true },
		DiagnosticUnderlineInfo = { sp = p.light_blue, undercurl = true },
		DiagnosticUnderlineHint = { sp = p.greyish_blue, undercurl = true },
		DiagnosticUnderlineOk = { sp = p.green, undercurl = true },
		DiagnosticDeprecated = { sp = p.error, strikethrough = true },
	}
end

return {
	ui = ui,
	syntax = syntax,
	links = links,
	diagnostics = diagnostics,
}
