local p = require('cobalt2.palette')

---@return table<string, vim.api.keyset.highlight>
local function ui()
  return {
    Normal = { fg = p.fg, bg = p.bg },
    NormalNC = { fg = p.fg, bg = p.bg },
    Cursor = { fg = p.yellow, bg = p.bg },
    CursorLine = { bg = p.cursor_line },
    CursorColumn = { bg = p.cursor_hover },
    CursorLineNr = { fg = p.yellow, bold = true },
    LineNr = { fg = p.light_grey, bg = p.bg },
    ColorColumn = { bg = p.dark_red },
    Visual = { bg = p.selection },
    VisualNOS = { bg = p.darker_blue },
    Search = { fg = p.black, bg = p.blue },
    IncSearch = { fg = p.black, bg = p.yellow },
    CurSearch = { fg = p.black, bg = p.yellow },
    MatchParen = { fg = p.fg, bg = p.dark_purple, bold = true },
    StatusLine = { fg = p.yellow, bg = p.cursor_line },
    StatusLineNC = { fg = p.fg, bg = p.cursor_line },
    StatusLineTerm = { fg = p.black, bg = p.green, bold = true },
    StatusLineTermNC = { fg = p.black, bg = p.green },
    TabLine = { fg = p.yellow, bg = p.cursor_hover },
    TabLineFill = { fg = p.light_grey, bg = p.bg_dark },
    TabLineSel = { fg = p.fg, bg = p.bg, bold = true },
    WinSeparator = { fg = p.grey },
    WinBar = { fg = p.yellow, bold = true },
    WinBarNC = { fg = p.yellow },
    VertSplit = { fg = p.grey },
    Pmenu = { fg = p.light_grey, bg = p.bg_float },
    PmenuSel = { fg = p.black, bg = p.yellow },
    PmenuSbar = { bg = p.grey },
    PmenuThumb = { bg = p.lighter_grey },
    NormalFloat = { fg = p.fg, bg = p.bg_float },
    FloatBorder = { fg = p.blue, bg = p.bg },
    FloatTitle = { fg = p.yellow, bg = p.darker_blue },
    FloatFooter = { link = 'FloatTitle' },
    FloatShadow = { bg = p.black, blend = 80 },
    FloatShadowThrough = { bg = p.black, blend = 100 },
    SignColumn = { fg = p.bg, bg = p.bg },
    Folded = { fg = p.light_grey, bg = p.cursor_line, italic = true },
    FoldColumn = { fg = p.grey, bg = p.bg },
    DiffAdd = { fg = p.green, bg = p.bg },
    DiffChange = { fg = p.green, bg = p.bg },
    DiffDelete = { fg = p.red, bg = p.bg },
    DiffText = { fg = p.fg, bg = p.bg, bold = true },
    Directory = { fg = p.blue },
    ErrorMsg = { fg = p.error },
    WarningMsg = { fg = p.light_yellow },
    ModeMsg = { bold = true },
    MoreMsg = { fg = p.blue },
    Question = { fg = p.green },
    NonText = { fg = p.grey, bg = p.bg },
    SpecialKey = { fg = p.light_blue, bg = p.bg },
    Whitespace = { fg = p.grey },
    WildMenu = { fg = p.blue, bg = p.yellow },
    Conceal = { fg = p.grey },
    SpellBad = { sp = p.red, undercurl = true },
    SpellCap = { sp = p.blue, undercurl = true },
    SpellLocal = { sp = p.green, undercurl = true },
    SpellRare = { sp = p.pink, undercurl = true },
    Todo = { fg = p.orange, italic = true },
    Error = { fg = p.fg, bg = p.error, italic = true },
    Added = { fg = p.green },
    Changed = { fg = p.blue },
    Removed = { fg = p.red },
    QuickFixLine = { bg = p.cursor_hover },
    MsgSeparator = { link = 'StatusLine' },
    TermCursor = { reverse = true },
    RedrawDebugNormal = { reverse = true },
    RedrawDebugClear = { bg = p.yellow },
    RedrawDebugComposed = { bg = p.green },
    RedrawDebugRecompose = { bg = p.red },
    ComplMatchIns = {},
    SnippetTabstop = { link = 'Visual' },
    SnippetTabstopActive = { link = 'SnippetTabstop' },
  }
end

---@return table<string, vim.api.keyset.highlight>
local function syntax()
  return {
    Comment = { fg = p.blue, italic = true },
    Constant = { fg = p.light_green },
    String = { fg = p.light_green },
    Character = { fg = p.pink },
    Number = { fg = p.pink },
    Boolean = { fg = p.pink, italic = true },
    Float = { fg = p.pink },
    Identifier = { fg = p.orange },
    Function = { fg = p.light_pink, italic = true },
    Statement = { fg = p.orange },
    Conditional = { fg = p.orange },
    Repeat = { fg = p.pink },
    Label = { fg = p.yellow },
    Operator = { fg = p.blue },
    Keyword = { fg = p.light_blue, italic = true },
    Exception = { fg = p.light_pink, italic = true },
    PreProc = { fg = p.orange },
    Include = { fg = p.pink, italic = true },
    Define = { fg = p.orange, italic = true },
    Macro = { fg = p.yellow },
    PreCondit = { fg = p.orange },
    Type = { fg = p.yellow },
    StorageClass = { fg = p.light_orange },
    Structure = { fg = p.blue, italic = true },
    Typedef = { fg = p.orange },
    Special = { fg = p.light_green },
    SpecialChar = { fg = p.pink },
    Tag = { fg = p.light_blue },
    Delimiter = { fg = p.dirty_blue },
    SpecialComment = { fg = p.light_green, italic = true },
    Debug = { fg = p.light_green, italic = true },
    Underlined = { fg = p.light_green, underline = true },
    Ignore = { fg = p.grey, italic = true },
    Title = { fg = p.green, bold = true },
  }
end

---@return table<string, string>
local function links()
  return {
    VertSplit = 'WinSeparator',
    WinBarNC = 'WinBar',
    DiffTextAdd = 'DiffText',
    EndOfBuffer = 'NonText',
    LineNrAbove = 'LineNr',
    LineNrBelow = 'LineNr',
    CursorLineSign = 'SignColumn',
    CursorLineFold = 'FoldColumn',
    PmenuKind = 'Pmenu',
    PmenuKindSel = 'PmenuSel',
    PmenuMatch = 'Pmenu',
    PmenuMatchSel = 'PmenuSel',
    PmenuExtra = 'Pmenu',
    PmenuExtraSel = 'PmenuSel',
    PreInsert = 'Added',
    ComplHint = 'NonText',
    ComplHintMore = 'MoreMsg',
    Substitute = 'Search',
    String = 'Constant',
    Character = 'Constant',
    Number = 'Constant',
    Boolean = 'Constant',
    Float = 'Number',
    Function = 'Identifier',
    Conditional = 'Statement',
    Repeat = 'Statement',
    Label = 'Statement',
    Operator = 'Statement',
    Keyword = 'Statement',
    Exception = 'Statement',
    Include = 'PreProc',
    Define = 'PreProc',
    Macro = 'PreProc',
    PreCondit = 'PreProc',
    StorageClass = 'Type',
    Structure = 'Type',
    Typedef = 'Type',
    Tag = 'Special',
    SpecialChar = 'Special',
    Delimiter = 'Special',
    SpecialComment = 'Special',
    Debug = 'Special',
    DiagnosticVirtualTextError = 'DiagnosticError',
    DiagnosticVirtualTextWarn = 'DiagnosticWarn',
    DiagnosticVirtualTextInfo = 'DiagnosticInfo',
    DiagnosticVirtualTextHint = 'DiagnosticHint',
    DiagnosticVirtualTextOk = 'DiagnosticOk',
    DiagnosticFloatingError = 'DiagnosticError',
    DiagnosticFloatingWarn = 'DiagnosticWarn',
    DiagnosticFloatingInfo = 'DiagnosticInfo',
    DiagnosticFloatingHint = 'DiagnosticHint',
    DiagnosticFloatingOk = 'DiagnosticOk',
    DiagnosticSignError = 'DiagnosticError',
    DiagnosticSignWarn = 'DiagnosticWarn',
    DiagnosticSignInfo = 'DiagnosticInfo',
    DiagnosticSignHint = 'DiagnosticHint',
    DiagnosticSignOk = 'DiagnosticOk',
    DiagnosticUnnecessary = 'Comment',
    LspInlayHint = 'NonText',
    ['@markup.raw'] = 'Comment',
    ['@markup.link'] = 'Identifier',
    ['@markup.heading'] = 'Title',
    ['@markup.link.url'] = 'Underlined',
    ['@markup.underline'] = 'Underlined',
    ['@comment.todo'] = 'Todo',
    ['@comment'] = 'Comment',
    ['@punctuation'] = 'Delimiter',
    ['@constant'] = 'Constant',
    ['@constant.builtin'] = 'Special',
    ['@constant.macro'] = 'Define',
    ['@keyword.directive'] = 'Define',
    ['@string'] = 'String',
    ['@string.escape'] = 'SpecialChar',
    ['@string.special'] = 'SpecialChar',
    ['@character'] = 'Character',
    ['@character.special'] = 'SpecialChar',
    ['@number'] = 'Number',
    ['@boolean'] = 'Boolean',
    ['@number.float'] = 'Float',
    ['@function'] = 'Function',
    ['@function.builtin'] = 'Special',
    ['@function.macro'] = 'Macro',
    ['@function.method'] = 'Function',
    ['@variable.parameter'] = 'Identifier',
    ['@variable.parameter.builtin'] = 'Special',
    ['@variable.member'] = 'Identifier',
    ['@property'] = 'Identifier',
    ['@attribute'] = 'Macro',
    ['@attribute.builtin'] = 'Special',
    ['@constructor'] = 'Special',
    ['@keyword.conditional'] = 'Conditional',
    ['@keyword.repeat'] = 'Repeat',
    ['@keyword.type'] = 'Structure',
    ['@label'] = 'Label',
    ['@operator'] = 'Operator',
    ['@keyword'] = 'Keyword',
    ['@keyword.exception'] = 'Exception',
    ['@variable'] = 'Identifier',
    ['@type'] = 'Type',
    ['@type.definition'] = 'Typedef',
    ['@module'] = 'Identifier',
    ['@keyword.import'] = 'Include',
    ['@keyword.debug'] = 'Debug',
    ['@tag'] = 'Tag',
    ['@tag.builtin'] = 'Special',
    ['@lsp.type.class'] = 'Structure',
    ['@lsp.type.comment'] = 'Comment',
    ['@lsp.type.decorator'] = 'Function',
    ['@lsp.type.enum'] = 'Structure',
    ['@lsp.type.enumMember'] = 'Constant',
    ['@lsp.type.function'] = 'Function',
    ['@lsp.type.interface'] = 'Structure',
    ['@lsp.type.macro'] = 'Macro',
    ['@lsp.type.method'] = 'Function',
    ['@lsp.type.namespace'] = 'Structure',
    ['@lsp.type.parameter'] = 'Identifier',
    ['@lsp.type.property'] = 'Identifier',
    ['@lsp.type.struct'] = 'Structure',
    ['@lsp.type.type'] = 'Type',
    ['@lsp.type.typeParameter'] = 'Typedef',
    ['@lsp.type.variable'] = 'Identifier',
  }
end

---@return table<string, vim.api.keyset.highlight>
local function diagnostics()
  return {
    DiagnosticError = { fg = p.error },
    DiagnosticWarn = { fg = p.yellow },
    DiagnosticInfo = { fg = p.light_blue },
    DiagnosticHint = { fg = p.greyish_blue },
    DiagnosticOk = { fg = p.green },
    DiagnosticUnderlineError = { sp = p.error, undercurl = true },
    DiagnosticUnderlineWarn = { sp = p.yellow, undercurl = true },
    DiagnosticUnderlineInfo = { sp = p.light_blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = p.greyish_blue, undercurl = true },
    DiagnosticUnderlineOk = { sp = p.green, undercurl = true },
    DiagnosticDeprecated = { sp = p.error, strikethrough = true },
  }
end

return {
  ui = ui,
  syntax = syntax,
  links = links,
  diagnostics = diagnostics,
}
